### ISSUE TITLE
Error building goals with latest version

### ISSUE THREAD

**Issue by toronb** [PLangHQ/plang#33]
=== Error Info === 
Step 'set %name% as "Dwight Shrewd"'

Getting following Error with version 0.1.0.5 when building any file. 

MacBook Pro M2 (ARM) 
MacOS 14.4

Error: "Could not find pr file .build/api/Llm/YouNeedToFillBalance/01. FetchRapydRedirectURL.pr. Maybe try to build again?. This step is defined in Goal at /api/Llm.goal. The location of it on drive should be /app/.build/api/Llm/YouNeedToFillBalance/01. FetchRapydRedirectURL.pr. in line 12 in YouNeedToFillBalance at file Llm.goal 👇\r\nCould not find pr file .build/api/Llm/YouNeedToFillBalance/01. FetchRapydRedirectURL.pr. Maybe try to build again?. This step is defined in Goal at /api/Llm.goal. The location of it on drive should be /app/.build/api/Llm/YouNeedToFillBalance/01. FetchRapydRedirectURL.pr. in line 7 in C# code 👇. \r\n\r\nYou might have to define your step bit more, try including variable type, such as %name%(string), %age%(number), %tags%(array).\r\n\r\nThe error occured in this line:\r\n\r\n\t7. return balance == null || balance <= 0;\r\n\r\nThe C# code is this:\r\n1. namespace PLangGeneratedCode\n2. {\n3.     public static class CheckBalanceAndCallGoal\n4.     {\n5.         public static bool ExecutePlangCode(long? balance)\n6.         {\n7.             return balance == null || balance <= 0;\n8.         }\n9.     }\n10. }\r\n\r\n in line 6 in Llm - POST at file Llm.goal 👇"

=== Stack trace ===
   at PLang.Building.StepBuilder.BuildStep(Goal goal, Int32 stepIndex, List`1 excludeModules, Int32 errorCount) in C:\Users\Ingi Gauti\source\repos\plang\PLang\Building\StepBuilder.cs:line 146
   at PLang.Building.GoalBuilder.BuildGoal(IServiceContainer container, String goalFileAbsolutePath, Int32 errorCount) in C:\Users\Ingi Gauti\source\repos\plang\PLang\Building\GoalBuilder.cs:line 71
   at PLang.Building.Builder.Start(IServiceContainer container) in C:\Users\Ingi Gauti\source\repos\plang\PLang\Building\Builder.cs:line 67

**Comment by ingig** [comment]
Thank you for the issue. 

Issue has been solve. You will need to get the latest version. Sorry about that. Here is the link https://github.com/PLangHQ/plang/releases

Let me know if it works ok and of course if it doesn't work.

**Comment by toronb** [comment]
great!
I can confirm it's fixed
