### ISSUE TITLE
Identity - move from blockchain identity

### ISSUE THREAD

**Issue by ingig** [PLangHQ/plang#40]
Currently Identity is created using Nethereum library, this creates a public blockchain address. This is not good as the Identity is used for signing data and it might happen that money is transferred to it. This is generally not a good thing having data signed and money on same key.

It should use other technology then the blockchain standard to create a private key to sign data.

**Comment by jayson687** [comment]
The best hackers I have seen are  d a r k w e b p r o g r a m m e r @ g m a i l . c o m   , they got me $15,000 via hack

**Comment by ingig** [comment]
Closed #46
